admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

graduate:
    resource: "@GraduateBundle/Controller/"
    type:     annotation
    prefix:   /graduate

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix:   /